### ISSUE TITLE
Discussion for OriginTrail Parachain Governance parameters (Extension of RFC 15 discussion)

### ISSUE THREAD

**Issue by NZT48** [OriginTrail/OT-RFC-repository#26]
# OriginTrail Parachain Governance Parameters

Dear OriginTrail Community,

The OriginTrail core development team is currently implementing OriginTrail Parachain Governance code modules, and would like to invite the technical community to provide feedback and insights on important governance parameters. This document is a continuation of the [OT-RFC-15](https://github.com/OriginTrail/OT-RFC-repository/issues/24) process and it builds upon previous collaborative efforts and feedback. As we continue to build a robust and decentralized governance framework, your input and insights are vital in shaping the future of the OriginTrail Parachain.

Below is a list of all relevant parameters and proposed initial values. Keep in mind those will also be subject to change through the governance process, so the suggested values are intended only for the initial implementation. Your comments and feedback are very appreciated!

## Referenda timeline

To ensure clarity, we want to provide an overview of the timeline for all referenda. Although the timeline length may vary, the structure remains the same regardless of the proposal's initiator.

![Image_1](https://wiki.polkadot.network/assets/images/gov1-timeline-69424fec137182a898f00c29a90fbdb1.png)
Image 1: Illustration of periods 

Once the proposal is submitted the Launch Period starts. During this period of indefinite length the voters can endorse proposals by bonding the same amount of tokens used by the depositor. Deposited tokens for endorsement will be returned once the proposal becomes a referendum. During the launch period, the proposal will compete with other proposals, and the one that gets to the top will be selected for a referendum when the next voting period starts.

After the proposal is selected for a referendum. Proposals initiated by the public will become a public referendum, while those initiated by the council will become council referenda. The voting period lasts 5 days, after which, if the proposal is approved, it will go through an enactment period. 

Approved proposal moves through the enactment period that can be of different lengths depending on who initiated the proposal in the first place, with emergency proposals being the fastest ones and the only ones that can be voted simultaneously with other referenda.

## Proposed governance parameters

The following are important governance parameters that may evolve over time as we progress through the governance phases. We have proposed initial values for these parameters and kindly request your feedback:

* Launch Period
    * Determines how long the public can select a proposal to hold a referendum on. Every five days, the highest-weighted proposal will be chosen.
    * Proposed value:  5 day
* Voting period
    * Specifies the duration for token holders to vote on a referendum (duration of a referendum).
    * Proposed value:  5 days
* Enactment period
    * Specifies the time required for a successful referendum to be implemented on the network.
    * Proposed value:  2 days
* Cool-off period
    * Specifies the period during which an external proposal may not be resubmitted after being vetoed.
    * Proposed value:  7 days
* Emergency voting period (Fast Track Voting Period)
    * Specifies the minimum voting period allowed for a fast-track referendum.
    * Proposed value:  3 Hours
* Minimum Deposit (proposal deposit)
    * Specifies the minimum amount required as a deposit for a public referendum proposal.
    * Proposed value:  1000 OTP
* Max votes
    * Specifies the maximum number of votes for an account. 
    * Proposed value:  100
* Maximum proposals
    * Specifies the maximum number of public proposals that can exist at any time.
    * Proposed value:  100
* Maximum deposits
    * Specifies the maximum number of deposits a public proposal may have at any time.
    * Proposed value:  100
* Maximum blacklisted
    * Specifies the maximum number of items which can be blacklisted.
    * Proposed value:  100
* Council motion duration
    * Specifies the duration for council members to vote on a motion. Motions may end in fewer blocks if enough votes are cast to determine the result.
    * Proposed value: 3 Days
* Maximum proposals in Council
    * Specifies the maximum number of motions in council allowed to be active in parallel.
    * Proposed value: 100
* Maximum members in Council
    * Specifies the maximum number of members in council. Initially it would be five but later that number would be increased.
    * Proposed value: 5
* Default vote for Council
    * Determines default vote strategy of the OTP council. Prime member vote acts as the default for other members of Council that fail to vote before the timeout.
    * Proposed value: More Than Majority Then Prime Default Vote

Your feedback on these proposed governance parameters is greatly appreciated as we strive to refine and improve them. We aim to  create a governance model together from the inception, one that empowers the community and fosters a thriving decentralized ecosystem on OriginTrail Parachain.

#TraceOn

**Comment by DalSlacker** [comment]
I would suggest changing Launch Period and Voting Period to 7 days, as that provides better access to all members of the community

**Comment by Valcyclovir** [comment]
I think these parameters are a great healthy way to kick start OTP Governance 1.0. We can adjust it as we go but everything seems reasonable to me. 5 days launch + 5 days voting + 2 days enactment seem like a reasonable amount of time from proposal to action. 

Good extension to the RFC 15.

**Comment by branarakic** [comment]
Thanks for the feedback folks! 

> I would suggest changing Launch Period and Voting Period to 7 days, as that provides better access to all members of the community

The idea of this proposal was to start with 5 days for the voting period so that the entire cycle is ideally shorter than two weeks (12 days end to end), so as a community we can move a bit more rapidly with the near-term pending updates. Over the course of several such voting cycles we see this shorter time being beneficial so we can be faster at the beginning. As a team we feel that 5 days would be a reasonably long period for everyone in the community to be able to participate.

Keep in mind that all these initial parameters are subject to change later through the governance process.
